import Head from "next/head";
import React from "react";
import {
  ResponsiveContainer,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  Legend,
} from "recharts";

import { aboutMe, data } from "@/utils/Data";

export default function about() {
  return (
    <>
      <Head>
        <title>Ale - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-32">
        <header className="bg-gray py-8 border-b-4 border-orange">
          {/* ==================== Header ==================== */}
          <div className="container mx-auto px-4">
            <h1 className="text-center text-4xl font-bold tracking-widest">
              About Me
            </h1>
          </div>
        </header>

        <main className="container mx-auto py-16 px-4 flex">
          {/* ==================== Radar Chart ==================== */}
          <div className="w-1/3">
            <RadarChart
              cx={300}
              cy={250}
              outerRadius={100}
              width={500}
              height={500}
              data={data}
            >
              <PolarGrid />
              <PolarAngleAxis dataKey="subject" stroke="white" />
              <PolarRadiusAxis stroke="transparent" />
              <Radar
                name="2023"
                dataKey="A"
                stroke="#ff003c"
                fill="#ff003c"
                fillOpacity={0.6}
              />
              <Radar
                name="2020"
                dataKey="B"
                stroke="#F06520"
                fill="#F06520"
                fillOpacity={0.6}
              />
              <Legend align="right" />
            </RadarChart>
          </div>

          {/* ==================== Text ==================== */}
          <section className="w-2/3 ml-8">
            <div className="mb-16">
              <h2 className="text-3xl font-bold mb-4 border-l-4 border-yellow pl-2 animate-pulse">
                Who Am I
              </h2>
              <p className="text-lg leading-7">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
            </div>
            <div className="mb-16">
              <h2 className="text-3xl font-bold mb-4 border-l-4 border-yellow pl-2 animate-pulse">
                What I Offer
              </h2>
              <p className="text-lg leading-7">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
            </div>
            <div className="mb-16">
              <h2 className="text-3xl font-bold mb-4 border-l-4 border-yellow pl-2 animate-pulse">
                Experiences
              </h2>
              <p className="text-lg leading-7">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
