import Head from "next/head";
import React from "react";

export default function contact() {
  return (
    <>
      <Head>
        <title>Ale - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="py-[300px]">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold mb-10">Get in Touch</h2>
          <form className="grid grid-cols-2 gap-6">
            <div>
              <label htmlFor="name" className="block font-medium mb-2">
                _Name
              </label>
              <input
                type="text"
                name="name"
                id="name"
                className="bg-transparent border-b w-full focus:outline-none focus:border-red transition duration-300 ease-in-out"
              />
            </div>
            <div>
              <label htmlFor="email" className="block font-medium mb-2">
                Email_
              </label>
              <input
                type="email"
                name="email"
                id="email"
                className="bg-transparent border-b w-full focus:outline-none focus:border-red transition duration-300 ease-in-out"
              />
            </div>
            <div className="col-span-2">
              <label htmlFor="message" className="block font-medium mb-2">
                Message_
              </label>
              <textarea
                name="message"
                id="message"
                rows="5"
                className="bg-transparent border-b w-full focus:outline-none focus:border-red transition duration-300 ease-in-out"
              ></textarea>
            </div>
            <div className="col-span-2 text-center">
              <button
                type="submit"
                className="py-2 px-6 bg-red text-white font-medium rounded-full"
              >
                <span className="relative z-0">
                  <span className="absolute -inset-0.5 bg-blue-400 rounded-full blur-sm"></span>
                  <span className="relative">Send</span>
                </span>
              </button>
            </div>
          </form>
        </div>
      </section>
    </>
  );
}
