import Head from "next/head";
import Link from "next/link";
import { AiOutlineGithub, AiOutlineInstagram } from "react-icons/ai";
import { FaLinkedinIn } from "react-icons/fa";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ale - Personal Portolfio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-end justify-center w-full h-screen text-center">
        {/* ==================== Video background ==================== */}
        <video
          src="/bg.mp4"
          autoPlay
          loop
          muted
          className="object-cover h-full w-full absolute -z-10"
        />

        {/* ==================== Main Section ==================== */}
        <div className="p-8 flex flex-col items-center justify-center duration-500 w-full">
          <h1 className="text-5xl lg:text-7xl">I am Ale</h1>
          <h1 className="text-5xl lg:text-7xl capitalize mb-12">
            <span className="text-red font-bold">Pentester</span> & Web Dev
          </h1>

          <div className="flex flex-row justify-center items-center gap-8">
            <Link href="/about" className="link">
              Learn more.
            </Link>
            <Link href="/projects" className="link">
              Projects
            </Link>
          </div>
        </div>

        {/* ==================== Social Icons ==================== */}
        <div className="hidden absolute left-20 top-44 z-10 md:flex flex-col gap-5 items-center">
          <div className="bg-red w-[1.5px] h-[250px]"></div>
          <Link href="https://github.com/Aplo0x" className="hover:text-red">
            <AiOutlineGithub size={25} />
          </Link>
          <Link
            href="https://www.instagram.com/aplo0x/"
            className="hover:text-red"
          >
            <AiOutlineInstagram size={25} />
          </Link>
          <Link
            href="https://www.linkedin.com/in/alexandre-fortunato-ribeiro/"
            className="hover:text-red"
          >
            <FaLinkedinIn size={25} />
          </Link>
        </div>
      </main>
    </>
  );
}
