import Head from "next/head";
import React from "react";

export default function projects() {
  return (
    <>
      <Head>
        <title>Ale - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-32">
        <div className="max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-extrabold sm:text-4xl">My Projects</h2>
          <p className="mt-4 max-w-2xl text-xl text-red">
            Here are some of my latest projects. Click on any of them to learn
            more!
          </p>
          <div className="mt-10 grid grid-cols-1 gap-10 sm:grid-cols-2 lg:grid-cols-3">
            {/* ==================== Project Card 1 ==================== */}
            <div className="card border rounded-md overflow-hidden transform hover:scale-105 transition duration-300">
              <img
                src="https://i0.wp.com/www.cienciaedados.com/wp-content/uploads/2022/01/3-Estrategias-Para-Trabalhar-com-Grandes-Conjuntos-de-Dados-em-Python.jpg?fit=1200%2C600&ssl=1"
                alt="Project 1"
                className="w-full h-48 object-cover rounded-t-md"
              />
              <div className="p-4">
                <h3 className="text-lg font-medium text-white mb-2">
                  Password Checker
                </h3>
                <p className="mb-4">
                  A simple password checker I created using Python and Jupyter Notebook, will be adding a generator in the near future
                </p>
                <a
                  href="https://github.com/Aplo0x/pwd_checker"
                  target="_blank"
                  className="inline-block px-4 py-2 text-white font-semibold rounded-md transition duration-300 link"
                >
                  Learn more
                </a>
              </div>
            </div>

            {/* ==================== Project Card 2 ==================== */}
            {/* <div className="card border rounded-md overflow-hidden transform hover:scale-105 transition duration-300">
              <img
                src="https://www.digitalsilk.com/wp-content/uploads/2022/09/website-development-process-1.jpg"
                alt="Project 2"
                className="w-full h-48 object-cover rounded-t-md"
              />
              <div className="p-4">
                <h3 className="text-lg font-medium text-white mb-2">
                  Project 2
                </h3>
                <p className=" mb-4">
                  Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                  accusantium doloremque laudantium.
                </p>
                <a
                  href="https://github.com/Aplo0x"
                  target="_blank"
                  className="inline-block px-4 py-2 text-white font-semibold rounded-md transition duration-300"
                >
                  Learn more
                </a>
              </div>
            </div> */}

            {/* ==================== Project Card 3 ==================== */}
            {/* <div className="card border rounded-md overflow-hidden transform hover:scale-105 transition duration-300">
              <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnetjmdQ6Lmgo5XLvq3YBUynmjW4Jhk5qUeg&usqp=CAU"
                alt="Project 3"
                className="w-full h-48 object-cover rounded-t-md"
              />
              <div className="p-4">
                <h3 className="text-lg font-medium text-white mb-2">
                  Project 3
                </h3>
                <p className="mb-4">
                  Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                  accusantium doloremque laudantium.
                </p>
                <a
                  href="https://github.com/Aplo0x"
                  target="_blank"
                  className="inline-block px-4 py-2 text-white font-semibold rounded-md transition duration-300"
                >
                  Learn more
                </a>
              </div>
            </div> */}
          </div>
        </div>
      </div>
    </>
  );
}
